version: "3.8"

services:
  frontend:
    build:
      context: ./user-registration-fe
      dockerfile: ./Dockerfile
    env_file:
      - ./user-registration-fe/.env
    ports:
      - "4173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./user-registration-be
      dockerfile: ./Dockerfile
    env_file:
      - ./user-registration-be/.env
    ports:
      - "3000:3000"
    container_name: main-api
    restart: always
    networks:
      - ll-network

networks:
  ll-network:
    driver: bridge
