version: '3.8'

services:
  frontend:
    image: lapin-admin
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3002:80"
    pull_policy: build
    env_file:
      - stack.env
    restart: always